-- Session Management Tables
-- Run this in Supabase SQL Editor
-- Created: December 13, 2025

-- ============================================
-- 1. DEV_CHAT_SESSIONS - Full conversation sessions
-- ============================================
CREATE TABLE IF NOT EXISTS dev_chat_sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,

    -- Who and what project
    user_id UUID NOT NULL REFERENCES dev_users(id),
    project_id UUID REFERENCES dev_projects(id),

    -- Session metadata
    title VARCHAR(255),                              -- Auto-generated or user-set title
    status VARCHAR(20) DEFAULT 'active',             -- active, ended, archived

    -- Timestamps
    started_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    ended_at TIMESTAMP WITH TIME ZONE,
    last_activity_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Stats
    message_count INT DEFAULT 0,
    total_tokens INT DEFAULT 0,
    total_cost_usd DECIMAL(10, 6) DEFAULT 0,

    -- Summary (generated by AI)
    summary TEXT,
    summary_generated_at TIMESTAMP WITH TIME ZONE,
    key_decisions JSONB,                             -- Array of key decisions made
    files_discussed JSONB,                           -- Array of files mentioned
    todos_generated JSONB                            -- Todos extracted from session
);

CREATE INDEX idx_chat_sessions_user ON dev_chat_sessions(user_id);
CREATE INDEX idx_chat_sessions_project ON dev_chat_sessions(project_id);
CREATE INDEX idx_chat_sessions_status ON dev_chat_sessions(status);
CREATE INDEX idx_chat_sessions_started ON dev_chat_sessions(started_at DESC);

-- ============================================
-- 2. DEV_CHAT_MESSAGES - Individual messages in sessions
-- ============================================
CREATE TABLE IF NOT EXISTS dev_chat_messages (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES dev_chat_sessions(id) ON DELETE CASCADE,

    -- Message content
    role VARCHAR(20) NOT NULL,                       -- 'user', 'assistant', 'system'
    content TEXT NOT NULL,

    -- Token tracking
    input_tokens INT DEFAULT 0,
    output_tokens INT DEFAULT 0,
    cost_usd DECIMAL(10, 6) DEFAULT 0,

    -- Metadata
    model VARCHAR(50),                               -- Which AI model responded
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Optional: code blocks extracted
    code_blocks JSONB                                -- [{language, code, file_path}]
);

CREATE INDEX idx_chat_messages_session ON dev_chat_messages(session_id);
CREATE INDEX idx_chat_messages_created ON dev_chat_messages(created_at);

-- ============================================
-- 3. DEV_SESSION_SUMMARIES - AI-generated summaries
-- ============================================
CREATE TABLE IF NOT EXISTS dev_session_summaries (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    session_id UUID NOT NULL REFERENCES dev_chat_sessions(id) ON DELETE CASCADE,

    -- Summary content
    summary TEXT NOT NULL,                           -- Main summary
    key_points JSONB,                                -- Bullet points of key items
    action_items JSONB,                              -- Things that need to be done
    decisions_made JSONB,                            -- Key decisions from session
    code_changes JSONB,                              -- Files modified/created

    -- For continuity (what to tell next Claude)
    context_for_next_session TEXT,                   -- "Here's what we were working on..."

    -- Metadata
    generated_by VARCHAR(50) DEFAULT 'gpt-4',        -- Which model generated this
    generated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- Token usage for summary generation
    tokens_used INT,
    cost_usd DECIMAL(10, 6)
);

CREATE INDEX idx_session_summaries_session ON dev_session_summaries(session_id);

-- ============================================
-- 4. DEV_PROJECT_DOCS - Central documentation hub
-- ============================================
CREATE TABLE IF NOT EXISTS dev_project_docs (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    project_id UUID REFERENCES dev_projects(id),

    -- Document info
    doc_type VARCHAR(50) NOT NULL,                   -- 'readme', 'todo', 'notes', 'changelog', 'architecture'
    title VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,

    -- Version tracking
    version INT DEFAULT 1,
    previous_version_id UUID REFERENCES dev_project_docs(id),

    -- Who/when
    created_by UUID REFERENCES dev_users(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_by UUID REFERENCES dev_users(id),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),

    -- AI-generated indicator
    ai_generated BOOLEAN DEFAULT FALSE,
    ai_source_session_id UUID REFERENCES dev_chat_sessions(id)
);

CREATE INDEX idx_project_docs_project ON dev_project_docs(project_id);
CREATE INDEX idx_project_docs_type ON dev_project_docs(doc_type);

-- ============================================
-- 5. VIEWS - Helpful aggregations
-- ============================================

-- Recent sessions with summary status
CREATE OR REPLACE VIEW dev_recent_sessions AS
SELECT
    s.id,
    s.user_id,
    u.name AS user_name,
    s.project_id,
    p.name AS project_name,
    s.title,
    s.status,
    s.started_at,
    s.ended_at,
    s.message_count,
    s.total_tokens,
    s.total_cost_usd,
    s.summary IS NOT NULL AS has_summary,
    EXTRACT(EPOCH FROM (COALESCE(s.ended_at, NOW()) - s.started_at)) / 60 AS duration_minutes
FROM dev_chat_sessions s
LEFT JOIN dev_users u ON s.user_id = u.id
LEFT JOIN dev_projects p ON s.project_id = p.id
ORDER BY s.started_at DESC;

-- ============================================
-- 6. FUNCTIONS - Auto-update session stats
-- ============================================

-- Function to update session stats when message is added
CREATE OR REPLACE FUNCTION update_session_stats()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE dev_chat_sessions
    SET
        message_count = message_count + 1,
        total_tokens = total_tokens + NEW.input_tokens + NEW.output_tokens,
        total_cost_usd = total_cost_usd + NEW.cost_usd,
        last_activity_at = NOW()
    WHERE id = NEW.session_id;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for message insert
DROP TRIGGER IF EXISTS trigger_update_session_stats ON dev_chat_messages;
CREATE TRIGGER trigger_update_session_stats
    AFTER INSERT ON dev_chat_messages
    FOR EACH ROW
    EXECUTE FUNCTION update_session_stats();

-- ============================================
-- Done! Tables created successfully.
-- ============================================
